name=flagsapi
version=1.0.1
author=WolodiaM <w.melnyk07@gmail.com>
maintainer=WolodiaM <w.melnyk07@gmail.com>
sentence=Library for packing bits
paragraph=Can use uint8_t(byte) and uint16_t(unsigned int) and pack 1, 2, 3 or 4 bits
category=Data Storage
url=https://github.com/WolodiaM/flagsapi-library
architectures=* 
includes=flagsapi.h

